[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.aws-sam
  | \.pytest_cache
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.venv-aws
  | _build
  | buck-out
  | build
  | dist
  | node_modules
)/
'''
