AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend resources associated with the BODS (Bus Open Data Service) service

Parameters:
  Environment:
    Type: String
    Description: The environment into which the stack is being deployed
  ProjectName:
    Description: The name of the project
    Type: String
  AvlConsumerApiBaseUrl:
    Type: String
    Default: 'https://6tfu67dcng.execute-api.eu-west-2.amazonaws.com/v1'
  CavlConsumerUrl:
    Type: String
    Default: 'https://api-consumer-cavl-internal.dev.itoworld.com'
  RdsDbHostAddr:
    Type: String
    Default: ''
  RdsDbPort:
    Type: Number
    Default: 5432
  DDGitData:
    Type: String
    Default: ''
    Description: 'The output of $(git rev-parse HEAD),$(git config --get remote.origin.url). Used for Datadog Source Code Integration tagging'
  Version:
    Type: String
    Default: 'unknown'
    Description: 'Version to pass to Datadog APM'
  FrontendBaseUrl:
    Type: String
    Default: 'https://bus-data.dft.gov.uk'
    Description: 'Frontend Base Url'

Resources:
  PeriodicTasks:
    Type: AWS::Serverless::Application
    Properties:
      Location: './periodic-tasks.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        AvlConsumerApiBaseUrl: !Ref AvlConsumerApiBaseUrl
        CavlConsumerUrl: !Ref CavlConsumerUrl
        RdsDbHostAddr: !Ref RdsDbHostAddr
        RdsDbPort: !Ref RdsDbPort
        BoilerplateLambdaLayerArn: !Ref BoilerplateLambdaLayer
        DDGitData: !Ref DDGitData
        Version: !Ref Version
      Tags:
        env: !Ref Environment
        service: !Sub '${ProjectName}-periodic-tasks'

  TimetablesEtl:
    Type: AWS::Serverless::Application
    DependsOn: PeriodicTasks
    Properties:
      Location: './timetables-etl.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        RdsDbHostAddr: !Ref RdsDbHostAddr
        RdsDbPort: !Ref RdsDbPort
        BoilerplateLambdaLayerArn: !Ref BoilerplateLambdaLayer
        DDGitData: !Ref DDGitData
        Version: !Ref Version
        FrontendBaseUrl: !Ref FrontendBaseUrl
      Tags:
        env: !Ref Environment
        service: !Sub '${ProjectName}-timetables-etl'

  FaresEtl:
    Type: AWS::Serverless::Application
    DependsOn: TimetablesEtl
    Properties:
      Location: './fares-etl.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        RdsDbHostAddr: !Ref RdsDbHostAddr
        RdsDbPort: !Ref RdsDbPort
        BoilerplateLambdaLayerArn: !Ref BoilerplateLambdaLayer
        DDGitData: !Ref DDGitData
        Version: !Ref Version
        FrontendBaseUrl: !Ref FrontendBaseUrl
      Tags:
        env: !Ref Environment
        service: !Sub '${ProjectName}-fares-etl'

  BoilerplateLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${ProjectName}-${Environment}-boilerplate-layer'
      ContentUri: ./src/boilerplate
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11
