AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Supporting services for the execution of the timetables ETL process

Parameters:
  Environment:
    Type: String
    Description: The environment into which the stack is being deployed
  ProjectName:
    Description: The name of the project
    Type: String
  SubFunction:
    Description: The sub-fuction that each resource relates to
    Type: String
    Default: 'tt'
  RdsDbHostAddr:
    Type: String
  RdsDbPort:
    Type: Number
  BoilerplateLambdaLayerArn:
    Type: String
  DynamoDBTableName:
    Type: String
    Default: ''

Conditions:
  IsNotLocal: !Not [!Equals [!Ref Environment, 'local']]
  IsNotProd: !Not [!Equals [!Ref Environment, 'prod']]
  UseDefaultTableName: !Equals [!Ref DynamoDBTableName, '']

Globals:
  Function:
    Architectures:
      - x86_64
    Runtime: python3.11
    Timeout: 60
    MemorySize: 256
    KmsKeyArn: !If
      - IsNotLocal
      - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
      - !Ref AWS::NoValue
    VpcConfig: !If
      - IsNotLocal
      - SubnetIds:
          - !Sub '{{resolve:ssm:/bodds/${Environment}/private-subnet-0}}'
          - !Sub '{{resolve:ssm:/bodds/${Environment}/private-subnet-1}}'
          - !Sub '{{resolve:ssm:/bodds/${Environment}/private-subnet-2}}'
        SecurityGroupIds:
          - !GetAtt CommonLambdaSecurityGroup.GroupId
      - !Ref AWS::NoValue
    Environment:
      Variables:
        HTTPS_PROXY: !If
          - IsNotLocal
          - !Sub 'http://squid.bodds.${Environment}:3128'
          - !Ref AWS::NoValue
        PROJECT_ENV: !Ref Environment
        PROJECT_NAME: !Ref ProjectName
        POSTGRES_HOST: !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/etl-rds-proxy-endpoint}}' ## UPDATE TO STANDARD POLICY ONCE ISOLATED TESTING COMPLETE
          - !Ref RdsDbHostAddr
        POSTGRES_PORT: !Ref RdsDbPort
        POSTGRES_DB: !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-db-name}}'
          - postgres
        POSTGRES_USER: !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/pg-rw-user}}'
          - bodds_rw
        DYNAMO_DB_TABLE_NAME: !Ref DynamoDBTableName

Resources:
  ##################################
  #### TIMETABLES STATE MACHINE ####
  ##################################
  TimetablesStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-${SubFunction}-sm'
      Role: !GetAtt TimetablesStateMachineRole.Arn
      DefinitionUri: './src/timetables_etl.statemachine.json'
      DefinitionSubstitutions:
        ClamAvScannerLambdaArn: !GetAtt ClamAvScannerLambda.Arn
        FileValidationLambdaArn: !GetAtt FileValidationLambda.Arn
        SchemaCheckLambdaArn: !GetAtt SchemaCheckLambda.Arn
        PostSchemaCheckLambdaArn: !GetAtt PostSchemaCheckLambda.Arn
        FileAttributesEtlLambdaArn: !GetAtt FileAttributesEtlLambda.Arn
        PtiValidationLambdaArn: !GetAtt PtiValidationLambda.Arn
        ExceptionHandlerLambdaArn: !GetAtt ExceptionHandlerLambda.Arn

  TimetablesStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-${SubFunction}-sm-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StateMachineLambdaInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt ClamAvScannerLambda.Arn
                  - !GetAtt FileValidationLambda.Arn
                  - !GetAtt SchemaCheckLambda.Arn
                  - !GetAtt PostSchemaCheckLambda.Arn
                  - !GetAtt FileAttributesEtlLambda.Arn
                  - !GetAtt PtiValidationLambda.Arn
                  - !GetAtt ExceptionHandlerLambda.Arn

  ##########################################
  #### TIMETABLES STATE MACHINE TRIGGER ####
  ##########################################
  TimetablesStateMachineTrigger:
    Type: AWS::Pipes::Pipe
    Condition: IsNotLocal
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-${SubFunction}-sm-trigger'
      Description: !Sub 'EventBridge Pipe used as trigger for ${ProjectName}-${Environment} Timetables ETL State Machine'
      RoleArn: !GetAtt TimetablesStateMachineTriggerRole.Arn
      KmsKeyIdentifier: !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
      Source: !GetAtt TimetablesProcessQueue.Arn
      Target: !GetAtt TimetablesStateMachine.Arn

  TimetablesStateMachineTriggerRole:
    Type: AWS::IAM::Role
    Condition: IsNotLocal
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-${SubFunction}-sm-trigger-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: pipes.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: 'StateMachineSQSPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource:
                  - !GetAtt TimetablesProcessQueue.Arn
        - PolicyName: StateMachineInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource:
                  - !GetAtt TimetablesStateMachine.Arn

  ################################
  #### CLAM AV SCANNER LAMBDA ####
  ################################
  ClamAvScannerLambda:
    Type: AWS::Serverless::Function
    ## checkov:skip=CKV_AWS_115:Ensure that AWS Lambda function is configured for function-level concurrent execution limit
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-${SubFunction}-clamav-scanner-lambda'
      Role: !GetAtt CommonLambdaExecutionRole.Arn
      CodeUri: ./src/timetables_etl
      Handler: clamav_scanner.lambda_handler
      Layers:
        - !Ref BoilerplateLambdaLayerArn
      Environment:
        Variables:
          CLAMAV_HOST: !Sub 'http://clamav.bodds.${Environment}'
          CLAMAV_PORT: 3310
      LoggingConfig:
        LogGroup: !Ref ClamAvScannerLambdaLogGroup

  ClamAvScannerLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-${SubFunction}-clamav-scanner-lambda'
      KmsKeyId: !If
        - IsNotLocal
        - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
        - !Ref AWS::NoValue
      RetentionInDays: 30

  ################################
  #### FILE VALIDATION LAMBDA ####
  ################################
  FileValidationLambda:
    Type: AWS::Serverless::Function
    ## checkov:skip=CKV_AWS_115:Ensure that AWS Lambda function is configured for function-level concurrent execution limit
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-${SubFunction}-file-validation-lambda'
      Role: !GetAtt CommonLambdaExecutionRole.Arn
      CodeUri: ./src/timetables_etl
      Handler: file_validation.lambda_handler
      Layers:
        - !Ref BoilerplateLambdaLayerArn
      LoggingConfig:
        LogGroup: !Ref FileValidationLambdaLogGroup

  FileValidationLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-${SubFunction}-file-validation-lambda'
      KmsKeyId: !If
        - IsNotLocal
        - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
        - !Ref AWS::NoValue
      RetentionInDays: 30

  #############################
  #### SCHEMA CHECK LAMBDA ####
  #############################
  SchemaCheckLambda:
    Type: AWS::Serverless::Function
    ## checkov:skip=CKV_AWS_115:Ensure that AWS Lambda function is configured for function-level concurrent execution limit
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-${SubFunction}-schema-check-lambda'
      Role: !GetAtt CommonLambdaExecutionRole.Arn
      CodeUri: ./src/timetables_etl
      Handler: schema_check.lambda_handler
      Layers:
        - !Ref BoilerplateLambdaLayerArn
      Environment:
        Variables:
          TXC_XSD_PATH: 'TransXChange_general.xsd'
      LoggingConfig:
        LogGroup: !Ref SchemaCheckLambdaLogGroup

  SchemaCheckLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-${SubFunction}-schema-check-lambda'
      KmsKeyId: !If
        - IsNotLocal
        - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
        - !Ref AWS::NoValue
      RetentionInDays: 30

  ##################################
  #### POST SCHEMA CHECK LAMBDA ####
  ##################################
  PostSchemaCheckLambda:
    Type: AWS::Serverless::Function
    ## checkov:skip=CKV_AWS_115:Ensure that AWS Lambda function is configured for function-level concurrent execution limit
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-${SubFunction}-post-schema-check-lambda'
      Role: !GetAtt CommonLambdaExecutionRole.Arn
      CodeUri: ./src/timetables_etl
      Handler: post_schema_check.lambda_handler
      Layers:
        - !Ref BoilerplateLambdaLayerArn
      LoggingConfig:
        LogGroup: !Ref PostSchemaCheckLambdaLogGroup

  PostSchemaCheckLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-${SubFunction}-post-schema-check-lambda'
      KmsKeyId: !If
        - IsNotLocal
        - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
        - !Ref AWS::NoValue
      RetentionInDays: 30

  ####################################
  #### FILE ATTRIBUTES ETL LAMBDA ####
  ####################################
  FileAttributesEtlLambda:
    Type: AWS::Serverless::Function
    ## checkov:skip=CKV_AWS_115:Ensure that AWS Lambda function is configured for function-level concurrent execution limit
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-${SubFunction}-file-attributes-etl-lambda'
      Role: !GetAtt CommonLambdaExecutionRole.Arn
      CodeUri: ./src/timetables_etl
      Handler: file_attributes_etl.lambda_handler
      Layers:
        - !Ref BoilerplateLambdaLayerArn
      LoggingConfig:
        LogGroup: !Ref FileAttributesEtlLambdaLogGroup

  FileAttributesEtlLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-${SubFunction}-file-attributes-etl-lambda'
      KmsKeyId: !If
        - IsNotLocal
        - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
        - !Ref AWS::NoValue
      RetentionInDays: 30

  ###############################
  #### PTI VALIDATION LAMBDA ####
  ###############################
  PtiValidationLambda:
    Type: AWS::Serverless::Function
    ## checkov:skip=CKV_AWS_115:Ensure that AWS Lambda function is configured for function-level concurrent execution limit
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-${SubFunction}-pti-validation-lambda'
      Role: !GetAtt CommonLambdaExecutionRole.Arn
      CodeUri: ./src/timetables_etl
      Handler: pti_validation.lambda_handler
      Layers:
        - !Ref BoilerplateLambdaLayerArn
      LoggingConfig:
        LogGroup: !Ref PtiValidationLambdaLogGroup

  PtiValidationLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-${SubFunction}-pti-validation-lambda'
      KmsKeyId: !If
        - IsNotLocal
        - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
        - !Ref AWS::NoValue
      RetentionInDays: 30

  ##################################
  #### EXCEPTION HANDLER LAMBDA ####
  ##################################
  ExceptionHandlerLambda:
    Type: AWS::Serverless::Function
    ## checkov:skip=CKV_AWS_115:Ensure that AWS Lambda function is configured for function-level concurrent execution limit
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-${SubFunction}-exception-handler-lambda'
      Role: !GetAtt CommonLambdaExecutionRole.Arn
      CodeUri: ./src/timetables_etl
      Handler: exception_handler.lambda_handler
      Layers:
        - !Ref BoilerplateLambdaLayerArn
      LoggingConfig:
        LogGroup: !Ref ExceptionHandlerLogGroup

  ExceptionHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-${SubFunction}-exception-handler-lambda'
      KmsKeyId: !If
        - IsNotLocal
        - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
        - !Ref AWS::NoValue
      RetentionInDays: 30

  #########################################
  #### GENERAL CONFIGURATION RESOURCES ####
  #########################################
  TimetablesCache:
    Type: AWS::DynamoDB::Table
    ## checkov:skip=CKV_AWS_28:Ensure DynamoDB point in time recovery (backup) is enabled
    Properties:
      TableName: !If
        - UseDefaultTableName
        - !Sub '${ProjectName}-${Environment}-${SubFunction}-cache'
        - !Ref DynamoDBTableName
      AttributeDefinitions:
        - AttributeName: Key
          AttributeType: S
      KeySchema:
        - AttributeName: Key
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If
          - IsNotProd
          - false
          - true
      SSESpecification:
        SSEEnabled: true
        SSEType: 'KMS'
        KMSMasterKeyId: !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
          - !Ref AWS::NoValue

  CommonLambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: IsNotLocal
    Properties:
      GroupDescription: !Sub 'Security group for ${ProjectName}-${Environment} Timetables ETL related lambda functions'
      GroupName: !Sub '${ProjectName}-${Environment}-${SubFunction}-common-lambda'
      SecurityGroupEgress:
        - IpProtocol: '-1'
          Description: 'Allow outbound connectivity to any'
          CidrIp: '0.0.0.0/0'
      VpcId: !Sub '{{resolve:ssm:/bodds/${Environment}/vpc-id}}'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-${SubFunction}-common-lambda'

  CommonLambdaSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Condition: IsNotLocal
    Properties:
      GroupId: !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-sg-id}}'
      Description: !Sub 'Allow inbound connectivity from ${ProjectName}-${Environment}-${SubFunction}-common-lambda'
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !GetAtt CommonLambdaSecurityGroup.GroupId

  CommonLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-${SubFunction}-common-lambda-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/etl-rds-proxy-rw-user-access-policy-arn}}' ## UPDATE TO STANDARD POLICY ONCE ISOLATED TESTING COMPLETE
          - 'arn:aws:iam::aws:policy/AmazonRDSFullAccess' # Full access fallback
        - !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/etl-rds-proxy-ro-user-access-policy-arn}}' ## UPDATE TO STANDARD POLICY ONCE ISOLATED TESTING COMPLETE
          - 'arn:aws:iam::aws:policy/AmazonRDSReadOnlyAccess' # Read-only fallback
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !If
                  - IsNotLocal
                  - !Sub '{{resolve:ssm:/bodds/${Environment}/s3/app/arn}}'
                  - '*'
              - Effect: Allow
                Action:
                  - s3:GetObject*
                  - s3:PutObject*
                Resource: !If
                  - IsNotLocal
                  - !Sub '{{resolve:ssm:/bodds/${Environment}/s3/app/arn}}'
                  - '*'
        - PolicyName: KMSAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:GenerateDataKey
                  - kms:Decrypt
                  - kms:Encrypt
                Resource: !If
                  - IsNotLocal
                  - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
                  - '*'
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource: !GetAtt TimetablesCache.Arn

  TimetablesProcessQueue:
    Type: AWS::SQS::Queue
    Condition: IsNotLocal
    Properties:
      QueueName: !Sub '${ProjectName}-${Environment}-${SubFunction}-process-queue'
      KmsMasterKeyId: !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TimetablesDeadLetterQueue.Arn
        maxReceiveCount: 3

  TimetablesDeadLetterQueue:
    Type: AWS::SQS::Queue
    Condition: IsNotLocal
    Properties:
      QueueName: !Sub '${ProjectName}-${Environment}-${SubFunction}-dead-letter-queue'
      KmsMasterKeyId: !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
      VisibilityTimeout: 300
