AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Supporting services for the execution of the timetables ETL process

Parameters:
  Environment:
    Type: String
    Description: The environment into which the stack is being deployed
  ProjectName:
    Description: The name of the project
    Type: String
  RdsDbHostAddr:
    Type: String
  RdsDbPort:
    Type: Number

Conditions:
  IsNotLocal: !Not [!Equals [!Ref Environment, 'local']]

Globals:
  Function:
    Architectures:
      - x86_64
    Runtime: python3.11
    Timeout: 60
    MemorySize: 256
    KmsKeyArn: !If
      - IsNotLocal
      - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
      - !Ref AWS::NoValue
    VpcConfig: !If
      - IsNotLocal
      - 
        SubnetIds:
          - !Sub '{{resolve:ssm:/bodds/${Environment}/private-subnet-0}}'
          - !Sub '{{resolve:ssm:/bodds/${Environment}/private-subnet-1}}'
          - !Sub '{{resolve:ssm:/bodds/${Environment}/private-subnet-2}}'
        SecurityGroupIds:
          - !GetAtt CommonLambdaSecurityGroup.GroupId
      - !Ref AWS::NoValue
    Environment:
      Variables:
        HTTPS_PROXY: !If
          - IsNotLocal
          - !Sub 'http://squid.bodds.${Environment}:3128'
          - !Ref AWS::NoValue
        PROJECT_ENV: !Ref Environment
        PROJECT_NAME: !Ref ProjectName
        POSTGRES_HOST: !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-endpoint}}'
          - !Ref RdsDbHostAddr
        POSTGRES_PORT: !Ref RdsDbPort
        POSTGRES_DB: !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-db-name}}'
          - postgres
        POSTGRES_USER: !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/pg-rw-user}}'
          - bodds_rw

Resources:
  ###########################
  #### ETL STATE MACHINE ####
  ###########################
  EtlStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-timetables-etl-sm'
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref PlaceholderLambda

        # - LambdaInvokePolicy:
        #     FunctionName: !Ref ScanAndUnpackLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref BasicFileValidationLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref SchemaValidationLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref PiiCheckLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref PtiValidationLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref FileAttributesEtlLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref TimetablesEtlLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref ExceptionHandlerLambda
        - S3ReadPolicy:
            BucketName: !Ref PlaceholderS3Bucket
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PlaceholderSNSTopic.TopicName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt PlaceholderSQSQueue.QueueName
      Events:
        S3ObjectCreatedEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - 'aws.s3'
              detail-type:
                - 'Object Created'
              detail:
                bucket:
                  name:
                    - !Ref PlaceholderS3Bucket
      DefinitionUri: './src/timetables_etl.statemachine.json'
      DefinitionSubstitutions:
        PlaceholderLambdaArn: !GetAtt PlaceholderLambda.Arn
        ExceptionHandlerLambdaArn: !GetAtt ExceptionHandlerLambda.Arn
        PlaceholderSNSTopicArn: !GetAtt PlaceholderSNSTopic.TopicArn
        PlaceholderSQSQueueUrl: !GetAtt PlaceholderSQSQueue.QueueUrl

  ############################
  #### PLACEHOLDER LAMBDA ####
  ############################
  PlaceholderLambda:
    Type: AWS::Serverless::Function
    ## checkov:skip=CKV_AWS_115:Ensure that AWS Lambda function is configured for function-level concurrent execution limit
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-placeholder-lambda'
      CodeUri: ./src/timetables_etl
      Handler: app.lambda_handler
      Layers:
        - !Ref BoilerplateLambdaLayer
      Policies:
        - 'AWSLambdaBasicExecutionRole'
        - 'AWSLambdaVPCAccessExecutionRole'
        - S3CrudPolicy:
            BucketName: !Ref PlaceholderS3Bucket
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - kms:GenerateDataKey
            Resource: !If
              - IsNotLocal
              - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
              - "*"
        - !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-rw-user-access-policy-arn}}'
          - "arn:aws:iam::aws:policy/AmazonRDSFullAccess" # Is this right? No such role as ReadWrite
        - !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-ro-user-access-policy-arn}}'
          - "arn:aws:iam::aws:policy/AmazonRDSReadOnlyAccess"
      LoggingConfig:
        LogGroup: !Ref PlaceholderLambdaLogGroup

  PlaceholderLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-placeholder-lambda'
      KmsKeyId: !If
      - IsNotLocal
      - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
      - !Ref AWS::NoValue 
      RetentionInDays: 30

  ##################################
  #### POST SCHEMA CHECK LAMBDA ####
  ##################################
  TimetablePostSchemaCheckLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-timetable-post-schema-check-lambda'
      CodeUri: ./src/timetables_etl
      Handler: app.lambda_handler
      Layers:
        - !Ref BoilerplateLambdaLayer
      Policies:
        - 'AWSLambdaBasicExecutionRole'
        - 'AWSLambdaVPCAccessExecutionRole'
        - S3CrudPolicy:
            BucketName: !Ref PlaceholderS3Bucket
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - kms:GenerateDataKey
              Resource: !If
                - IsNotLocal
                - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
                - "*"
        - !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-rw-user-access-policy-arn}}'
          - "arn:aws:iam::aws:policy/AmazonRDSFullAccess" # Is this right? No such role as ReadWrite
        - !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-ro-user-access-policy-arn}}'
          - "arn:aws:iam::aws:policy/AmazonRDSReadOnlyAccess"
      LoggingConfig:
        LogGroup: !Ref TimetablePostSchemaCheckLambdaLogGroup

  TimetablePostSchemaCheckLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-timetable-post-schema-check-lambda'
      KmsKeyId: !If
        - IsNotLocal
        - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
        - !Ref AWS::NoValue
      RetentionInDays: 30

  ##################################
  #### EXCEPTION HANDLER LAMBDA ####
  ##################################
  ExceptionHandlerLambda:
    Type: AWS::Serverless::Function
    ## checkov:skip=CKV_AWS_115:Ensure that AWS Lambda function is configured for function-level concurrent execution limit
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-exception-handler-lambda'
      CodeUri: ./src/timetables_etl
      Handler: exception_handler.lambda_handler
      Layers:
        - !Ref BoilerplateLambdaLayer
      Policies:
        - 'AWSLambdaBasicExecutionRole'
        - 'AWSLambdaVPCAccessExecutionRole'
        - S3CrudPolicy:
            BucketName: !Ref PlaceholderS3Bucket
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - kms:GenerateDataKey
            Resource: !If
              - IsNotLocal
              - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
              - "*"
        - !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-rw-user-access-policy-arn}}'
          - "arn:aws:iam::aws:policy/AmazonRDSFullAccess" # Is this right? No such role as ReadWrite
        - !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-ro-user-access-policy-arn}}'
          - "arn:aws:iam::aws:policy/AmazonRDSReadOnlyAccess"
      LoggingConfig:
        LogGroup: !Ref ExceptionHandlerLogGroup

  ExceptionHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-exception-handler-lambda'
      KmsKeyId: !If
      - IsNotLocal
      - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
      - !Ref AWS::NoValue 
      RetentionInDays: 30

  #########################################
  #### GENERAL CONFIGURATION RESOURCES ####
  #########################################
  PlaceholderS3Bucket:
    # Temporarily suppress warning on placeholder items
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_56
            comment: 'Ensure S3 bucket has RestrictPublicBuckets enabled'
          - id: CKV_AWS_55
            comment: 'Ensure S3 bucket has ignore public ACLs enabled'
          - id: CKV_AWS_54
            comment: 'Ensure S3 bucket has block public policy enabled'
          - id: CKV_AWS_21
            comment: 'Ensure the S3 bucket has versioning enabled'
          - id: CKV_AWS_53
            comment: 'Ensure S3 bucket has block public ACLs enabled'
          - id: CKV_AWS_18
            comment: 'Ensure the S3 bucket has access logging enabled'
    Type: AWS::S3::Bucket

  PlaceholderSNSTopic:
    # Temporarily suppress warning on placeholder items
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_26
            comment: 'Ensure all data stored in the SNS topic is encrypted'
    Type: AWS::SNS::Topic

  PlaceholderSQSQueue:
    # Temporarily suppress warning on placeholder items
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_27
            comment: 'Ensure all data stored in the SQS queue is encrypted'
    Type: AWS::SQS::Queue

  CommonLambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: IsNotLocal
    Properties:
      GroupDescription: !Sub 'Security group for ${ProjectName}-${Environment} ETL related lambda functions'
      GroupName: !Sub '${ProjectName}-${Environment}-etl-common-lambda'
      SecurityGroupEgress:
        - IpProtocol: '-1'
          Description: 'Allow outbound connectivity to any'
          CidrIp: '0.0.0.0/0'
      VpcId: !Sub '{{resolve:ssm:/bodds/${Environment}/vpc-id}}'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-etl-common-lambda'

  CommonLambdaSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Condition: IsNotLocal
    Properties:
      GroupId: !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-sg-id}}'
      Description: !Sub 'Allow inbound connectivity from ${ProjectName}-${Environment}-etl-common-lambda'
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !GetAtt CommonLambdaSecurityGroup.GroupId

  BoilerplateLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${ProjectName}-${Environment}-etl-boilerplate-layer'
      ContentUri: ./src/boilerplate
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11
