AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Supporting services for the execution of the timetables ETL process

Parameters:
  Environment:
    Type: String
    Description: The environment into which the stack is being deployed
  ProjectName:
    Description: The name of the project
    Type: String
  RdsDbHostAddr:
    Type: String
  RdsDbPort:
    Type: Number

Conditions:
  IsNotLocal: !Not [!Equals [!Ref Environment, 'local']]

Globals:
  Function:
    Architectures:
      - x86_64
    Runtime: python3.11
    Timeout: 60
    MemorySize: 256
    VpcConfig:
      SubnetIds:
        - !Sub '{{resolve:ssm:/bodds/${Environment}/private-subnet-0}}'
        - !Sub '{{resolve:ssm:/bodds/${Environment}/private-subnet-1}}'
        - !Sub '{{resolve:ssm:/bodds/${Environment}/private-subnet-2}}'
      SecurityGroupIds:
        - !GetAtt CommonLambdaSecurityGroup.GroupId

Resources:
  ###########################
  #### ETL STATE MACHINE ####
  ###########################
  EtlStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-timetables-etl-sm'
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref PlaceholderLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref ScanAndUnpackLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref BasicFileValidationLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref SchemaValidationLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref PiiCheckLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref PtiValidationLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref FileAttributesEtlLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref TimetablesEtlLambda
        # - LambdaInvokePolicy:
        #     FunctionName: !Ref ExceptionHandlerLambda
        - S3ReadPolicy:
            BucketName: !Ref PlaceholderS3Bucket
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PlaceholderSNSTopic.TopicName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt PlaceholderSQSQueue.QueueName
      Events:
        S3ObjectCreatedEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - 'aws.s3'
              detail-type:
                - 'Object Created'
              detail:
                bucket:
                  name:
                    - !Ref PlaceholderS3Bucket
      DefinitionUri: './src/timetables_etl.statemachine.yaml'
      DefinitionSubstitutions:
        PlaceholderLambdaArn: !GetAtt PlaceholderLambda.Arn
        PlaceholderSNSTopicArn: !GetAtt PlaceholderSNSTopic.TopicArn
        PlaceholderSQSQueueUrl: !GetAtt PlaceholderSQSQueue.QueueUrl

  ############################
  #### PLACEHOLDER LAMBDA ####
  ############################
  PlaceholderLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-placeholder-lambda'
      CodeUri: ./src/timetables_etl
      Handler: app.lambda_handler
      Layers:
        - !Ref BoilerplateLambdaLayer
      Policies:
        - 'AWSLambdaBasicExecutionRole'
        - 'AWSLambdaVPCAccessExecutionRole'
        - S3CrudPolicy:
            BucketName: !Ref PlaceholderS3Bucket
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - kms:GenerateDataKey
            Resource: !Sub '{{resolve:ssm:/bodds/${Environment}/s3-kms-key-arn}}'
        - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-rw-user-access-policy-arn}}'
        - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-ro-user-access-policy-arn}}'
      Environment:
        Variables:
          HTTPS_PROXY: !If
            - IsNotLocal
            - !Sub 'http://squid.bodds.${Environment}:3128'
            - !Ref AWS::NoValue
          PROJECT_ENV: !Ref Environment
          PROJECT_NAME: !Ref ProjectName
          POSTGRES_HOST: !If
            - IsNotLocal
            - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-endpoint}}'
            - !Ref RdsDbHostAddr
          POSTGRES_PORT: !Ref RdsDbPort
          POSTGRES_DB: !If
            - IsNotLocal
            - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-db-name}}'
            - postgres
          POSTGRES_USER: !If
            - IsNotLocal
            - !Sub '{{resolve:ssm:/bodds/${Environment}/pg-rw-user}}'
            - bodds_rw
      LoggingConfig:
        LogGroup: !Ref PlaceholderLambdaLogGroup

  PlaceholderLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-placeholder-lambda'
      RetentionInDays: 30

  #########################################
  #### GENERAL CONFIGURATION RESOURCES ####
  #########################################
  PlaceholderS3Bucket:
    Type: AWS::S3::Bucket

  PlaceholderSNSTopic:
    Type: AWS::SNS::Topic

  PlaceholderSQSQueue:
    Type: AWS::SQS::Queue

  CommonLambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: IsNotLocal
    Properties:
      GroupDescription: !Sub 'Security group for ${ProjectName}-${Environment} ETL related lambda functions'
      GroupName: !Sub '${ProjectName}-${Environment}-etl-common-lambda'
      SecurityGroupEgress: 
        - IpProtocol: '-1'
          CidrIp: '0.0.0.0/0'
      VpcId: !Sub '{{resolve:ssm:/bodds/${Environment}/vpc-id}}'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-etl-common-lambda'

  CommonLambdaSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Condition: IsNotLocal
    Properties:
      GroupId: !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-sg-id}}'
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !GetAtt CommonLambdaSecurityGroup.GroupId

  BoilerplateLambdaLayer: 
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${ProjectName}-${Environment}-etl-boilerplate-layer'
      ContentUri: ./src/boilerplate
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11