AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Supporting services for the execution of the timetables ETL process

Parameters:
  Environment:
    Type: String
    Description: The environment into which the stack is being deployed
  ProjectName:
    Description: The name of the project
    Type: String
  RdsDbHostAddr:
    Type: String
  RdsDbPort:
    Type: Number

Conditions:
  IsNotLocal: !Not [!Equals [!Ref Environment, 'local']]

Globals:
  Function:
    Architectures:
      - x86_64
    Runtime: python3.11
    Timeout: 60
    MemorySize: 256
    KmsKeyArn: !If
      - IsNotLocal
      - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
      - !Ref AWS::NoValue
    VpcConfig: !If
      - IsNotLocal
      - 
        SubnetIds:
          - !Sub '{{resolve:ssm:/bodds/${Environment}/private-subnet-0}}'
          - !Sub '{{resolve:ssm:/bodds/${Environment}/private-subnet-1}}'
          - !Sub '{{resolve:ssm:/bodds/${Environment}/private-subnet-2}}'
        SecurityGroupIds:
          - !GetAtt CommonLambdaSecurityGroup.GroupId
      - !Ref AWS::NoValue
    Environment:
      Variables:
        HTTPS_PROXY: !If
          - IsNotLocal
          - !Sub 'http://squid.bodds.${Environment}:3128'
          - !Ref AWS::NoValue
        PROJECT_ENV: !Ref Environment
        PROJECT_NAME: !Ref ProjectName
        POSTGRES_HOST: !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-endpoint}}'
          - !Ref RdsDbHostAddr
        POSTGRES_PORT: !Ref RdsDbPort
        POSTGRES_DB: !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-db-name}}'
          - postgres
        POSTGRES_USER: !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/pg-rw-user}}'
          - bodds_rw

Resources:
  ###########################
  #### ETL STATE MACHINE ####
  ###########################
  EtlStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-timetables-etl-sm'
      Role: !GetAtt EtlStateMachineRole.Arn
      Events:
        S3ObjectCreatedEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - 'aws.s3'
              detail-type:
                - 'Object Created'
              detail:
                bucket:
                  name:
                    - !Ref PlaceholderS3Bucket
      DefinitionUri: './src/timetables_etl.statemachine.json'
      DefinitionSubstitutions:
        ExceptionHandlerLambdaArn: !GetAtt ExceptionHandlerLambda.Arn
        PlaceholderSNSTopicArn: !GetAtt PlaceholderSNSTopic.TopicArn
        PlaceholderSQSQueueUrl: !GetAtt PlaceholderSQSQueue.QueueUrl
        ClamAvScannerLambdaArn: !GetAtt ClamAvScannerLambda.Arn
        TimetablePostSchemaCheckLambdaArn: !GetAtt TimetablePostSchemaCheckLambda.Arn
  EtlStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StateMachineLambdaInvokePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt ClamAvScannerLambda.Arn
                  - !GetAtt TimetablePostSchemaCheckLambda.Arn
        - PolicyName: SNSPublishPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !GetAtt PlaceholderSNSTopic.TopicArn
        - PolicyName: SQSSendMessagePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt PlaceholderSQSQueue.Arn

  ################################
  #### CLAM AV SCANNER LAMBDA ####
  ################################
  ClamAvScannerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-clam-av-scanner-lambda'
      CodeUri: ./src/timetables_etl
      Handler: clam_av_scanner.lambda_handler
      Layers:
        - !Ref BoilerplateLambdaLayer
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          CLAMAV_HOST: !Sub 'http://clamav.bodds.${Environment}'
          CLAMAV_PORT: 3310
      LoggingConfig:
        LogGroup: !Ref ClamAvScannerLambdaLogGroup

  ClamAvScannerLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-clam-av-scanner-lambda'
      KmsKeyId: !If
        - IsNotLocal
        - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
        - !Ref AWS::NoValue
      RetentionInDays: 30

  ##################################
  #### POST SCHEMA CHECK LAMBDA ####
  ##################################
  TimetablePostSchemaCheckLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-timetable-post-schema-check-lambda'
      CodeUri: ./src/timetables_etl
      Handler: timetable_post_schema_check.lambda_handler
      Layers:
        - !Ref BoilerplateLambdaLayer
      Role: !GetAtt LambdaExecutionRole.Arn
      LoggingConfig:
        LogGroup: !Ref TimetablePostSchemaCheckLambdaLogGroup

  TimetablePostSchemaCheckLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-timetable-post-schema-check-lambda'
      KmsKeyId: !If
        - IsNotLocal
        - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
        - !Ref AWS::NoValue
      RetentionInDays: 30

  ##################################
  #### EXCEPTION HANDLER LAMBDA ####
  ##################################
  ExceptionHandlerLambda:
    Type: AWS::Serverless::Function
    ## checkov:skip=CKV_AWS_115:Ensure that AWS Lambda function is configured for function-level concurrent execution limit
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-exception-handler-lambda'
      CodeUri: ./src/timetables_etl
      Handler: exception_handler.lambda_handler
      Layers:
        - !Ref BoilerplateLambdaLayer
      Role: !GetAtt LambdaExecutionRole.Arn
      LoggingConfig:
        LogGroup: !Ref ExceptionHandlerLogGroup

  ExceptionHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-exception-handler-lambda'
      KmsKeyId: !If
      - IsNotLocal
      - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
      - !Ref AWS::NoValue 
      RetentionInDays: 30

  ###############################
  #### LAMBDA EXECUTION ROLE ####
  ###############################
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-rw-user-access-policy-arn}}'
          - "arn:aws:iam::aws:policy/AmazonRDSFullAccess"  # Full access fallback
        - !If
          - IsNotLocal
          - !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-ro-user-access-policy-arn}}'
          - "arn:aws:iam::aws:policy/AmazonRDSReadOnlyAccess"  # Read-only fallback
      Policies:
        - PolicyName: LambdaLogGroupPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:PutRetentionPolicy
                  - logs:DeleteLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${PlaceholderS3Bucket}"
                  - !Sub "arn:aws:s3:::${PlaceholderS3Bucket}/*"
        - PolicyName: KMSAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kms:GenerateDataKey
                  - kms:Decrypt
                  - kms:Encrypt
                Resource: !If
                  - IsNotLocal
                  - !Sub '{{resolve:ssm:/bodds/${Environment}/kms-key-arn}}'
                  - "*"

  #########################################
  #### GENERAL CONFIGURATION RESOURCES ####
  #########################################
  PlaceholderS3Bucket:
    # Temporarily suppress warning on placeholder items
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_56
            comment: 'Ensure S3 bucket has RestrictPublicBuckets enabled'
          - id: CKV_AWS_55
            comment: 'Ensure S3 bucket has ignore public ACLs enabled'
          - id: CKV_AWS_54
            comment: 'Ensure S3 bucket has block public policy enabled'
          - id: CKV_AWS_21
            comment: 'Ensure the S3 bucket has versioning enabled'
          - id: CKV_AWS_53
            comment: 'Ensure S3 bucket has block public ACLs enabled'
          - id: CKV_AWS_18
            comment: 'Ensure the S3 bucket has access logging enabled'
    Type: AWS::S3::Bucket

  PlaceholderSNSTopic:
    # Temporarily suppress warning on placeholder items
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_26
            comment: 'Ensure all data stored in the SNS topic is encrypted'
    Type: AWS::SNS::Topic

  PlaceholderSQSQueue:
    # Temporarily suppress warning on placeholder items
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_27
            comment: 'Ensure all data stored in the SQS queue is encrypted'
    Type: AWS::SQS::Queue

  CommonLambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: IsNotLocal
    Properties:
      GroupDescription: !Sub 'Security group for ${ProjectName}-${Environment} ETL related lambda functions'
      GroupName: !Sub '${ProjectName}-${Environment}-etl-common-lambda'
      SecurityGroupEgress:
        - IpProtocol: '-1'
          Description: 'Allow outbound connectivity to any'
          CidrIp: '0.0.0.0/0'
      VpcId: !Sub '{{resolve:ssm:/bodds/${Environment}/vpc-id}}'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-etl-common-lambda'

  CommonLambdaSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Condition: IsNotLocal
    Properties:
      GroupId: !Sub '{{resolve:ssm:/bodds/${Environment}/rds-proxy-sg-id}}'
      Description: !Sub 'Allow inbound connectivity from ${ProjectName}-${Environment}-etl-common-lambda'
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !GetAtt CommonLambdaSecurityGroup.GroupId

  BoilerplateLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${ProjectName}-${Environment}-etl-boilerplate-layer'
      ContentUri: ./src/boilerplate
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11
