name: 'Create GitHub Check'
description: 'Creates a GitHub check with a title and summary'

inputs:
  name:
    description: 'Name of the check'
    required: true
  title:
    description: 'Title of the check'
    required: true
  summary:
    description: 'Summary content of the check'
    required: true
  conclusion:
    description: 'Conclusion of the check (success/failure)'
    required: true
  token:
    description: 'GitHub token'
    required: true
  commit-sha:
    description: 'Commit SHA'
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        json_payload=$(jq -n \
          --arg name "${{ inputs.name }}" \
          --arg head_sha "${{ inputs.commit-sha }}" \
          --arg conclusion "${{ inputs.conclusion }}" \
          --arg title "${{ inputs.title }}" \
          --arg summary "${{ inputs.summary }}" \
          '{
            name: $name,
            head_sha: $head_sha,
            status: "completed",
            conclusion: $conclusion,
            output: {
              title: $title,
              summary: $summary
            }
          }')

        response=$(curl -L \
          -w "\n%{http_code}" \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/check-runs \
          -d "$json_payload")

        status_code=$(echo "$response" | tail -n1)
        if [ "$status_code" -ge 400 ]; then
          echo "Error creating check: $response"
          exit 1
        fi
        echo "Response from GitHub API:"
        echo "$response"
