name: 'Create GitHub Check'
description: 'Creates a GitHub check with a title and summary'

inputs:
  name:
    description: 'Name of the check'
    required: true
  title:
    description: 'Title of the check'
    required: true
  summary:
    description: 'Summary content of the check'
    required: true
  conclusion:
    description: 'Conclusion of the check (success/failure)'
    required: true
    default: 'neutral'
  token:
    description: 'GitHub token'
    required: true
  commit-sha:
    description: 'Commit SHA'
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        # Print inputs for debugging (masking sensitive data)
        echo "Creating check:"
        echo "Name: ${{ inputs.name }}"
        echo "Title length: ${#INPUT_TITLE}"
        echo "Summary length: ${#INPUT_SUMMARY}"
        echo "Original conclusion: ${{ inputs.conclusion }}"

        # Set conclusion to neutral if invalid
        if [[ ! "${{ inputs.conclusion }}" =~ ^(success|failure|neutral|cancelled|timed_out|action_required|skipped)$ ]]; then
          echo "Warning: Invalid conclusion '${{ inputs.conclusion }}'. Defaulting to 'neutral'"
          CONCLUSION="neutral"
        else
          CONCLUSION="${{ inputs.conclusion }}"
        fi

        json_payload=$(jq -n \
          --arg name "${{ inputs.name }}" \
          --arg head_sha "${{ inputs.commit-sha }}" \
          --arg conclusion "$CONCLUSION" \
          --arg title "${{ inputs.title }}" \
          --arg summary "${{ inputs.summary }}" \
          '{
            name: $name,
            head_sha: $head_sha,
            status: "completed",
            conclusion: $conclusion,
            output: {
              title: $title,
              summary: $summary
            }
          }')

        response=$(curl -L \
          -w "\n%{http_code}" \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/check-runs \
          -d "$json_payload")

        status_code=$(echo "$response" | tail -n1)
        if [ "$status_code" -ge 400 ]; then
          echo "Error creating check: $response"
          exit 1
        fi
